version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: GateMaster
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
    depends_on:
      - mongo-db
  mongo-db:
    container_name: mongodb
    image: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
